### ISSUE TITLE
Error: String could not be parsed as XML

### ISSUE THREAD

**Issue by cletsimon** [Hyra/PHPUnit-Cake2#16]
```
cake Phpunit.Phpunit

App : app
Path: /Users/cletsimon/Sites/test_app/app/
---------------------------------------------------------------
Hi There. To install PHPUnit, run `Phpunit.Phpunit install [version]`
Possible versions:
Warning Error: file_get_contents(http://pear.phpunit.de/feed.xml): failed to open stream: HTTP request failed! HTTP/1.1 410 Gone
 in [/Users/cletsimon/Sites/test_app/lib/Cake/Utility/Xml.php, line 101]

2015-03-17 06:02:42 Warning: file_get_contents(http://pear.phpunit.de/feed.xml): failed to open stream: HTTP request failed! HTTP/1.1 410 Gone
 in [/Users/cletsimon/Sites/test_app/lib/Cake/Utility/Xml.php, line 101]
Error: String could not be parsed as XML
#0 /Users/cletsimon/Sites/test_app/lib/Cake/Utility/Xml.php(123): SimpleXMLElement->__construct('', 16384)
#1 /Users/cletsimon/Sites/test_app/lib/Cake/Utility/Xml.php(102): Xml::_loadXml(false, Array)
#2 /Users/cletsimon/Sites/test_app/app/Plugin/Phpunit/Console/Command/PhpunitShell.php(410): Xml::build('http://pear.php...')
#3 /Users/cletsimon/Sites/test_app/app/Plugin/Phpunit/Console/Command/PhpunitShell.php(346): PhpunitShell->_pearInfoXml()
#4 /Users/cletsimon/Sites/test_app/app/Plugin/Phpunit/Console/Command/PhpunitShell.php(316): PhpunitShell->_pearInfo()
#5 /Users/cletsimon/Sites/test_app/app/Plugin/Phpunit/Console/Command/PhpunitShell.php(119): PhpunitShell->_getVersions()
#6 /Users/cletsimon/Sites/test_app/app/Plugin/Phpunit/Console/Command/PhpunitShell.php(68): PhpunitShell->versions()
#7 /Users/cletsimon/Sites/test_app/lib/Cake/Console/Shell.php(393): PhpunitShell->main()
#8 /Users/cletsimon/Sites/test_app/lib/Cake/Console/ShellDispatcher.php(201): Shell->runCommand(NULL, Array)
#9 /Users/cletsimon/Sites/test_app/lib/Cake/Console/ShellDispatcher.php(69): ShellDispatcher->dispatch()
#10 /Users/cletsimon/Sites/test_app/app/Console/cake.php(33): ShellDispatcher::run(Array)
#11 {main}
```

**Comment by Hyra** [comment]
It looks like they have removed `http://pear.phpunit.de/feed.xml`
